### ISSUE TITLE
Reproduce miniImageNet results

### ISSUE THREAD

**Issue by ByeonggeunKim** [yiren-jian/LabelHalluc#3]
Hi, Yiren. 

Thanks very much for sharing your code, and I am really interested in reproducing your works.
However, I have difficulty in reproducing the results especially for miniImageNet.

I run the code with below hyperparameters as provided in README.md.
* 5-way 5-shot
CUDA_VISIBLE_DEVICES=0,1 python -W ignore eval_fewshot_SoftPseudoLabel.py --dataset miniImageNet --data_root data/miniImageNet/ --model_path models_pretrained/mini_IER_distilled.pth --n_shot 5 --n_aug_support 5 --epoch 1 --norm_feat
* 5-way 1shot
CUDA_VISIBLE_DEVICES=0,1 python -W ignore eval_fewshot_SoftPseudoLabel.py --dataset miniImageNet --data_root data/miniImageNet/ --model_path models_pretrained/mini_IER_distilled.pth --n_shot 1 --n_aug_support 25 --early 150 --norm_feat

It gives us accuracies of 67.32 and 86.08 for 1 and 5 shot experiments, respectively, which are lower than 68.28 and 86.54 reported in your manuscript.
It would be really appreciate, if you can share the hyperparameters while you use the 'mini_IER_distilled.pth' as the pretrained weights.

Thank you.

**Comment by yiren-jian** [comment]
Hi bungkun,

Thanks for your interest in our work!

TL,DR: the training and evaluation are done with 600 random episodes, which means that you can get different results in different runs (because the model is seeing different episodes). 

I have re-run the experiments of 5-way miniImageNet with IER-distilled twice and attached the training logs at https://github.com/yiren-jian/LabelHalluc/tree/master/training_logs/miniImageNet. As you can see, in log1, LabelHalluc is 86.73 and log2 85.87. 

But what really matter is the comparison between acc1 (IER baseline) and acc2 (LabelHalluc) in training logs. acc1 and acc2 is the direct comparison between IER and ours, using the **exact same** episodes. i.e., even in log2 where LabelHalluc is 85.87, IER is only 84.01 (both numbers are below what reported, but the improvement is +1.86). In log1, IER 84.66 and LabelHalluc 86.73 are both above what reported, but the improvement is +2.07.

More on acc1 and acc2: 
In each episode, we follow the fixed embedding and linear regression protocol in prior works (RFS, SKD or IER) to get acc1. Then, we retrain the model using hallucinated base examples and test on this same episode to get acc2. 

Best,
Yiren

**Comment by ByeonggeunKim** [comment]
Thank you for the quick reply.
It helps us a lot.

Best.
